@:enum abstract ChannelType(Int) {
	var CHANNEL_RGB = 0;
	var CHANNEL_RED = 1;
	var CHANNEL_GREEN = 2;
	var CHANNEL_BLUE = 3;
	var CHANNEL_ALPHA = 4;
	var CHANNEL_RED_COLORIZE = 5;
	var CHANNEL_GREEN_COLORIZE = 6;
	var CHANNEL_BLUE_COLORIZE = 7;
	var CHANNEL_RGB_STRAIGHT = 8;
	var CHANNEL_ALPHA_OVERLAY = 9;
	var CHANNEL_ALPHA_BOUNDARY = 10;
}
