@:enum abstract ParagraphJustification(Int) {
	var LEFT_JUSTIFY = 0;
	var CENTER_JUSTIFY = 1;
	var RIGHT_JUSTIFY = 2;
	var FULL_JUSTIFY_LASTLINE_LEFT = 3;
	var FULL_JUSTIFY_LASTLINE_RIGHT = 4;
	var FULL_JUSTIFY_LASTLINE_CENTER = 5;
	var FULL_JUSTIFY_LASTLINE_FULL = 6;
	var MULTIPLE_JUSTIFICATIONS = 7;
}
