@:enum abstract PREFType(Int) {
	var PREF_Type_MACHINE_SPECIFIC = 0;
	var PREF_Type_MACHINE_INDEPENDENT = 1;
	var PREF_Type_MACHINE_INDEPENDENT_RENDER = 2;
	var PREF_Type_MACHINE_INDEPENDENT_OUTPUT = 3;
	var PREF_Type_MACHINE_INDEPENDENT_COMPOSITION = 4;
	var PREF_Type_MACHINE_SPECIFIC_TEXT = 5;
	var PREF_Type_MACHINE_SPECIFIC_PAINT = 6;
}
