extern class Project {
	var readonly:Dynamic;
	var file:haxe.extern.EitherType<File, Null<Dynamic>>;
	var rootFolder:FolderItem;
	var items:ItemCollection;
	var activeItem:haxe.extern.EitherType<Item, Null<Dynamic>>;
	var bitsPerChannel:Float;
	var transparencyGridThumbnails:Bool;
	var numItems:Float;
	var selection:Array<Item>;
	var renderQueue:RenderQueue;
	var timeDisplayType:TimeDisplayType;
	var toolType:ToolType;
	var footageTimecodeDisplayStartType:FootageTimecodeDisplayStartType;
	var framesUseFeetFrames:Bool;
	var feetFramesFilmType:FeetFramesFilmType;
	var gpuAccelType:GpuAccelType;
	var framesCountType:FramesCountType;
	var displayStartFrame:Float;
	var linearBlending:Bool;
	var xmpPacket:String;
	function item(index:Float):Item;
	function consolidateFootage():Float;
	function removeUnusedFootage():Float;
	function reduceProject(array_of_items:Array<Item>):Float;
	function close(closeOptions:CloseOptions):Bool;
	function save(?file:File):Void;
	function saveWithDialog():Bool;
	function importPlaceholder(name:String, width:Float, height:Float, frameRate:Float, duration:Float):PlaceholderItem;
	function importFile(importOptions:ImportOptions):Item;
	function importFileWithDialog():haxe.extern.EitherType<Array<Item>, Null<Dynamic>>;
	function showWindow(doShow:Bool):Void;
	function autoFixExpressions(oldText:String, newText:String):Void;
	function newTeamProject(teamProjectName:String, description:String):Bool;
	function openTeamProject(teamProjectName:String):Bool;
	function shareTeamProject(comment:String):Bool;
	function syncTeamProject():Bool;
	function closeTeamProject():Bool;
	function convertTeamProjectToProject(project_file:File):Bool;
	function listTeamProjects():Array<String>;
	function isTeamProjectOpen(teamProjectName:String):Bool;
	function isAnyTeamProjectOpen():Bool;
	function isTeamProjectEnabled():Bool;
	function isLoggedInToTeamProject():Bool;
	function isSyncCommandEnabled():Bool;
	function isShareCommandEnabled():Bool;
	function isResolveCommandEnabled():Bool;
	function resolveConflict(ResolveType:ResolveType):Bool;
}
